spring:
  jackson:
    default-property-inclusion: non_null
  zipkin:
    enabled: ${ZIPKIN_ENABLED:true}
    base-url: ${ZIPKIN_URL:http://localhost:9411/}
  cloud:
    config:
      override-none: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
bitrix:
  enabled: true
logistics:
  enabled: true
  register-sellers: true
content-url: https://content.gdesemena.ru
web-url: https://gdesemena.ru